/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Projeto_soma.view;

import Projeto_soma.dao.SomaDao;
import Projeto_soma.modelo.Soma;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lab
 */
public class FmrSoma extends javax.swing.JFrame {

    /**
     * Creates new form FmrSoma
     */
    public FmrSoma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valor1 = new javax.swing.JTextField();
        valor2 = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Btnok = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Pesquisar = new javax.swing.JButton();
        alterar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSoma = new javax.swing.JTable();
        cbcons = new javax.swing.JComboBox();
        txtconsultar = new javax.swing.JTextField();
        btnconsultar = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor1ActionPerformed(evt);
            }
        });
        getContentPane().add(valor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 35, -1));
        getContentPane().add(valor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 41, -1));
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 41, -1));

        jLabel1.setText("+");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 10, 20));

        jLabel2.setText("=");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 10, -1));

        Btnok.setText("ok");
        Btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnokActionPerformed(evt);
            }
        });
        getContentPane().add(Btnok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 60, -1));

        jLabel3.setText("Pesquisar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        Pesquisar.setText("Pesquisar");
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(Pesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        alterar.setText("Alterar");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });
        getContentPane().add(alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jButton3.setText("Relatorio");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        tblSoma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Valor 1", "Valor 2", "Total"
            }
        ));
        tblSoma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSomaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSoma);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, 150));

        cbcons.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "codigo", "1º valor", "2º valor", "Total" }));
        cbcons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbconsActionPerformed(evt);
            }
        });
        getContentPane().add(cbcons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        txtconsultar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtconsultarKeyPressed(evt);
            }
        });
        getContentPane().add(txtconsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 80, -1));

        btnconsultar.setText("consultar");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnconsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        btnexcluir.setText("Excluir");
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnexcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 70, 20));

        jButton1.setText("Relatorio Rapido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnokActionPerformed
      double v1,v2,t;
      
      v1 = Double.parseDouble( valor1.getText());
      v2 = Double.parseDouble( valor2.getText());
     
      t = v1 +v2 ;
      
      total.setText(String.valueOf(t));
      
        Soma s = new Soma();
        
        s.setValor1(v1);
        s.setValor2(v2);
        s.setTotal(t);
      
        
        SomaDao sdao = new SomaDao();
        
        sdao.Adicionar(s);
        JOptionPane.showMessageDialog(null, "Soma cadastrada com sucesso");
    }//GEN-LAST:event_BtnokActionPerformed

    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarActionPerformed
     SomaDao cdao = new SomaDao();
       Soma c = new Soma();
       String campo = "cod_soma";
       
       cdao.pesquisar(campo, txtid.getText(), c);
       
       txtid.setText(""+c.getCod_soma());
       valor1.setText(""+c.getValor1());
       valor2.setText(""+c.getValor2());
       total.setText(""+c.getTotal());
       
      
    }//GEN-LAST:event_PesquisarActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
           Soma c = new Soma();
        
        c.setValor1(Double.parseDouble(valor1.getText()));
        c.setValor2(Double.parseDouble(valor2.getText()));
        c.setTotal(Double.parseDouble(total.getText()));
        c.setCod_soma(Integer.parseInt(txtid.getText()));
         
         SomaDao cdao= new SomaDao();
         cdao.altera(c);
         JOptionPane.showMessageDialog(null, "Soma alterado com sucesso");
          btnconsultarActionPerformed(evt);
    }//GEN-LAST:event_alterarActionPerformed

    private void cbconsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbconsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbconsActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        SomaDao sdao = new SomaDao();
        Soma s = new Soma();
        
        String campo =null;
        
        if (cbcons.getSelectedIndex()==0) {
            campo = "cod_soma";
        }else if (cbcons.getSelectedIndex()==1){
            campo = "valor1";
        }else if (cbcons.getSelectedIndex()==2){
            campo = "valor2";
        }else if (cbcons.getSelectedIndex()==3){
            campo = "total";
        }
        
        sdao.pesquisar(campo, txtconsultar.getText(),s);
        
        txtid.setText(""+s.getCod_soma());
        valor1.setText(String.valueOf(s.getValor1()));
        valor2.setText(String.valueOf(s.getValor2()));
        total.setText(String.valueOf(s.getTotal()));
        
        List<Soma> somas = sdao.getLista(campo, txtconsultar.getText());
        DefaultTableModel model = (DefaultTableModel) tblSoma.getModel();
        model.setNumRows(0);
        
        for (Soma so : somas){
            model.addRow(new Object[]{
                so.getCod_soma(),
                so.getValor1(),
                so.getValor2(),
                so.getTotal()
            });
        }
        if (valor1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Soma não encontrada");
        } 
        
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void valor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor1ActionPerformed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
  Soma s = new Soma();
  
  int r = JOptionPane.showConfirmDialog(null,"Deseja excluir esse registro");
  if(r == 0){
      s.setCod_soma(Integer.parseInt(txtid.getText()));
      SomaDao sdao = new SomaDao();
      sdao.remover(s);
      
      JOptionPane.showMessageDialog(null, "Soma Removida com Sucesso");
      btnconsultarActionPerformed(evt);
             }
  
    }//GEN-LAST:event_btnexcluirActionPerformed

    private void tblSomaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSomaMouseClicked
        if(evt.getClickCount()==1){
            txtid.setText(tblSoma.getValueAt(tblSoma.getSelectedRow(),0).toString());
            valor1.setText(tblSoma.getValueAt(tblSoma.getSelectedRow(),1).toString());
            valor2.setText(tblSoma.getValueAt(tblSoma.getSelectedRow(),2).toString());
            total.setText(tblSoma.getValueAt(tblSoma.getSelectedRow(),3).toString());
        }
    }//GEN-LAST:event_tblSomaMouseClicked

    private void txtconsultarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconsultarKeyPressed
        btnconsultarActionPerformed(null);

    }//GEN-LAST:event_txtconsultarKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
SomaDao d = new SomaDao();
d.Rel();
d.ChamaRel();
    }//GEN-LAST:event_jButton3ActionPerformed

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        SomaDao d = new SomaDao();

        d.GerarRel();

    }//GEN-LAST:event_jButton1ActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmrSoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmrSoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmrSoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmrSoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmrSoma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnok;
    private javax.swing.JButton Pesquisar;
    private javax.swing.JButton alterar;
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JComboBox cbcons;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSoma;
    private javax.swing.JTextField total;
    private javax.swing.JTextField txtconsultar;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField valor1;
    private javax.swing.JTextField valor2;
    // End of variables declaration//GEN-END:variables
}
