/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javalocadora;

import Locadora.modelo.Cliente;
import Conection.Conexao;
import Locadora.dao.ClienteDao;
import java.sql.Connection;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author 8680213
 */
public class Cliente_CL extends javax.swing.JFrame {
    
    public Connection con;
    public Statement st;
    public int estado_cliente;
    public int idcliente;
    
    
    /**
     * Creates new form Cliente
     */
    public Cliente_CL() {
        initComponents();
        Conexao CL_Cliente = new Conexao ();
        CL_NOME.setEnabled(false);
        CL_RG.setEnabled(false);
        CL_CPF.setEnabled(false);
        CL_DATA_NASCIMENTO.setEnabled(false);
        CL_RUA.setEnabled(false);
        CL_NUMERO.setEnabled(false);
        CL_BAIRRO.setEnabled(false);
        CL_CEP.setEnabled(false);
        CL_CIDADE.setEnabled(false);
        CL_ESTADO.setEnabled(false);
        CL_EMAIL.setEnabled(false);
        CL_DATA_CADASTRO.setEnabled(false);
        CL_TELEFONE_FIXO.setEnabled(false);
        CL_CELULAR_1.setEnabled(false);
        CL_CELULAR_2.setEnabled(false);
        CL_CELULAR_3.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CL_NOME = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CL_RG = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CL_CPF = new javax.swing.JTextField();
        label_dataNascimento = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CL_BAIRRO = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CL_RUA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CL_CIDADE = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CL_CEP = new javax.swing.JTextField();
        CL_EMAIL = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CL_TELEFONE_FIXO = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        CL_CELULAR_3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        CL_DATA_CADASTRO = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        CL_ID = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        btn_gravar = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        CL_NUMERO = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        CL_ESTADO = new javax.swing.JTextField();
        CL_CELULAR_2 = new javax.swing.JTextField();
        CL_CELULAR_1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        CL_DATA_NASCIMENTO = new javax.swing.JFormattedTextField();
        btn_pesquisar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        jPanel1.add(CL_NOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 400, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("RG:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));
        jPanel1.add(CL_RG, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 160, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("CPF:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));
        jPanel1.add(CL_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 170, -1));

        label_dataNascimento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_dataNascimento.setText("Data Nascimento :");
        jPanel1.add(label_dataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Bairro:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));
        jPanel1.add(CL_BAIRRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 170, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Rua:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));
        jPanel1.add(CL_RUA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 320, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Cidade:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));
        jPanel1.add(CL_CIDADE, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("CEP:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));
        jPanel1.add(CL_CEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 170, -1));
        jPanel1.add(CL_EMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, 160, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Email:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Celular");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));
        jPanel1.add(CL_TELEFONE_FIXO, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 120, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Telefone Fixo:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));
        jPanel1.add(CL_CELULAR_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 120, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Data de Cadastro:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, -1, -1));
        jPanel1.add(CL_DATA_CADASTRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 590, 110, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setText("Código Cliente:");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        CL_ID.setEditable(false);
        CL_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CL_IDActionPerformed(evt);
            }
        });
        jPanel1.add(CL_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 50, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Novo");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 120, 40));

        btn_gravar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_gravar.setText("Gravar");
        btn_gravar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gravarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_gravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 130, 40));

        btn_alterar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 670, 150, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Voltar");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 670, 120, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Nº");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, -1, -1));
        jPanel1.add(CL_NUMERO, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 40, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Estado");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));
        jPanel1.add(CL_ESTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 40, -1));
        jPanel1.add(CL_CELULAR_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 120, -1));
        jPanel1.add(CL_CELULAR_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 120, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("DADOS PESSOAIS");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("ENDEREÇO");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("CONTATO");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        try {
            CL_DATA_NASCIMENTO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CL_DATA_NASCIMENTO.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        CL_DATA_NASCIMENTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CL_DATA_NASCIMENTOActionPerformed(evt);
            }
        });
        jPanel1.add(CL_DATA_NASCIMENTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 110, -1));

        btn_pesquisar.setText("PESQUISAR CPF");
        btn_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));

        btn_excluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_excluir.setText("Excluir");
        btn_excluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 670, 140, 40));

        jButton1.setText("LIMPAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 600, -1, -1));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fundo_cliente.jpg"))); // NOI18N
        jLabel20.setAutoscrolls(true);
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 670, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu obj = new Menu();
        obj.setVisible(true);
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_gravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gravarActionPerformed
       
        
        Cliente cl = new Cliente();
        try {
                
                
        
        cl.setNome(CL_NOME.getText());
        cl.setCpf(CL_CPF.getText());
        cl.setBairro(CL_BAIRRO.getText());
        cl.setCelular1(CL_CELULAR_1.getText());
        cl.setCelular2(CL_CELULAR_1.getText());
        cl.setCelular3(CL_CELULAR_1.getText());
        cl.setCep(CL_CEP.getText());
        cl.setCidade(CL_CIDADE.getText());
        cl.setRg(CL_RG.getText());
        cl.setData_cad(CL_DATA_CADASTRO.getText());
        cl.setData_nasc(CL_DATA_NASCIMENTO.getText());
        cl.setEmail(CL_EMAIL.getText());
        cl.setEstado(CL_ESTADO.getText());
        cl.setTel_fixo(CL_TELEFONE_FIXO.getText());
        cl.setRua(CL_RUA.getText());
        cl.setNum(CL_NUMERO.getText());

        } catch (Exception e) {
            
        }
      
        
        ClienteDao cdao = new ClienteDao();
        cdao.Adiciona(cl);
        JOptionPane.showMessageDialog(null,"Cliente Cadastrado com Sucesso");
         
    }//GEN-LAST:event_btn_gravarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        CL_NOME.setEnabled(true);
        CL_RG.setEnabled(true);
        CL_CPF.setEnabled(true);
        CL_DATA_NASCIMENTO.setEnabled(true);
        CL_RUA.setEnabled(true);
        CL_NUMERO.setEnabled(true);
        CL_BAIRRO.setEnabled(true);
        CL_CEP.setEnabled(true);
        CL_CIDADE.setEnabled(true);
        CL_ESTADO.setEnabled(true);
        CL_EMAIL.setEnabled(true);
        CL_DATA_CADASTRO.setEnabled(true);
        CL_TELEFONE_FIXO.setEnabled(true);
        CL_CELULAR_1.setEnabled(true);
        CL_CELULAR_2.setEnabled(true);
        CL_CELULAR_3.setEnabled(true);
        CL_ID.setEditable(true);
        
        CL_NOME.setText("");
        CL_RG.setText("");
        CL_CPF.setText("");
        CL_DATA_NASCIMENTO.setText("");
        CL_RUA.setText("");
        CL_NUMERO.setText("");
        CL_BAIRRO.setText("");
        CL_CEP.setText("");
        CL_CIDADE.setText("");
        CL_ESTADO.setText("");
        CL_EMAIL.setText("");
        CL_DATA_CADASTRO.setText("");
        CL_TELEFONE_FIXO.setText("");
        CL_CELULAR_1.setText("");
        CL_CELULAR_2.setText("");
        CL_CELULAR_3.setText("");  
        CL_ID.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarActionPerformed
    ClienteDao cdao = new ClienteDao();
    Cliente c = new Cliente();
    String campo = "cpf";
    
    cdao.Consulta(campo, CL_CPF.getText(), c, jLabel1);
        
    if (CL_CPF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o CPF");
        } else {
    CL_NOME.setText(""+c.getNome());
    CL_CPF.setText(c.getCpf());
    CL_RG.setText(c.getRg());
    CL_BAIRRO.setText(c.getBairro());
    CL_CELULAR_1.setText(c.getCelular1());
    CL_CELULAR_2.setText(c.getCelular2());    
    CL_CELULAR_3.setText(c.getCelular3());
    CL_CEP.setText(c.getCep());
    CL_CIDADE.setText(c.getCidade());
    CL_DATA_CADASTRO.setText(c.getData_cad());
    CL_DATA_NASCIMENTO.setText(c.getData_nasc());
    CL_EMAIL.setText(c.getEmail());
    CL_ESTADO.setText(c.getEstado());
    CL_ID.setText(String.valueOf(c.getId()));
    CL_RG.setText(c.getRg());
    CL_RUA.setText(c.getRua());
    CL_TELEFONE_FIXO.setText(c.getTel_fixo());
    CL_NUMERO.setText(c.getNum());
    CL_ID.setText(String.valueOf(c.getId()));
    }
    }//GEN-LAST:event_btn_pesquisarActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
    Cliente cl = new Cliente();

        try {
        cl.setNome(CL_NOME.getText());
        cl.setCpf(CL_CPF.getText());
        cl.setBairro(CL_BAIRRO.getText());
        cl.setCelular1(CL_CELULAR_1.getText());
        cl.setCelular2(CL_CELULAR_1.getText());
        cl.setCelular3(CL_CELULAR_1.getText());
        cl.setCep(CL_CEP.getText());
        cl.setCidade(CL_CIDADE.getText());
        cl.setData_cad(CL_DATA_CADASTRO.getText());
        cl.setData_nasc(CL_DATA_NASCIMENTO.getText());
        cl.setEmail(CL_EMAIL.getText());
        cl.setEstado(CL_ESTADO.getText());
        //cl.setId(Integer.parseInt(CL_ID.getText()));
        cl.setRg(CL_RG.getText());
        cl.setRua(CL_RUA.getText());
        cl.setNum(CL_NUMERO.getText());
        cl.setTel_fixo(CL_TELEFONE_FIXO.getText());
        
            
        }catch (Exception e){
            
        }
        ClienteDao cdao = new ClienteDao();
        cdao.Alterar(cl);
        JOptionPane.showMessageDialog(null,"Cadastro Alterado com Sucesso");
    
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        Cliente cl = new Cliente();
        int r = JOptionPane.showConfirmDialog(null, "Deseja excluir esse Cadastro ?");
            if(r==0){
                cl.setId(Integer.parseInt(CL_ID.getText()));
                ClienteDao cdao = new ClienteDao();
                cdao.remove(cl);
                JOptionPane.showMessageDialog(null, "Cadastro Excluido com Sucesso");
                
            }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CL_NOME.setText("");
        CL_RG.setText("");
        CL_CPF.setText("");
        CL_DATA_NASCIMENTO.setText("");
        CL_RUA.setText("");
        CL_NUMERO.setText("");
        CL_BAIRRO.setText("");
        CL_CEP.setText("");
        CL_CIDADE.setText("");
        CL_ESTADO.setText("");
        CL_EMAIL.setText("");
        CL_DATA_CADASTRO.setText("");
        CL_TELEFONE_FIXO.setText("");
        CL_CELULAR_1.setText("");
        CL_CELULAR_2.setText("");
        CL_CELULAR_3.setText("");   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CL_DATA_NASCIMENTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CL_DATA_NASCIMENTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CL_DATA_NASCIMENTOActionPerformed

    private void CL_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CL_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CL_IDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente_CL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente_CL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente_CL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente_CL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente_CL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CL_BAIRRO;
    private javax.swing.JTextField CL_CELULAR_1;
    private javax.swing.JTextField CL_CELULAR_2;
    private javax.swing.JTextField CL_CELULAR_3;
    private javax.swing.JTextField CL_CEP;
    private javax.swing.JTextField CL_CIDADE;
    private javax.swing.JTextField CL_CPF;
    private javax.swing.JTextField CL_DATA_CADASTRO;
    private javax.swing.JFormattedTextField CL_DATA_NASCIMENTO;
    private javax.swing.JTextField CL_EMAIL;
    private javax.swing.JTextField CL_ESTADO;
    private javax.swing.JTextField CL_ID;
    private javax.swing.JTextField CL_NOME;
    private javax.swing.JTextField CL_NUMERO;
    private javax.swing.JTextField CL_RG;
    private javax.swing.JTextField CL_RUA;
    private javax.swing.JTextField CL_TELEFONE_FIXO;
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_gravar;
    private javax.swing.JButton btn_pesquisar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_dataNascimento;
    // End of variables declaration//GEN-END:variables
}
