/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javalocadora;

import Locadora.dao.LocacaoDao;
import Locadora.modelo.Locacao;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author julio
 */
public class Devolucao_1 extends javax.swing.JFrame {

    /**
     * Creates new form Devolucao_1
     */
    public Devolucao_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TXT_CPF = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBL_CONS = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txt_codloc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TXT_DEV = new javax.swing.JTextField();
        juros = new javax.swing.JTextField();
        atraso = new javax.swing.JTextField();
        TXT_VAL = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        calc = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btn_voltar_FCN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TOTAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));
        getContentPane().add(TXT_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 270, -1));

        jButton3.setText("BUSCAR CPF");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 19, -1, -1));

        TBL_CONS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CODIGO LOCAÇÃO", "FILME", "CLIENTE"
            }
        ));
        TBL_CONS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_CONSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBL_CONS);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 650, 190));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CPF");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 21, -1, -1));
        getContentPane().add(txt_codloc, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 120, -1));

        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DIAS DE ATRASO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("VALOR SEM JUROS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CODIGO LOCAÇÃO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DATA DEVOLUÇÃO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("JUROS % / DIA");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));
        getContentPane().add(TXT_DEV, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 170, -1));
        getContentPane().add(juros, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 170, -1));
        getContentPane().add(atraso, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 70, -1));
        getContentPane().add(TXT_VAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 70, -1));
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 140, 30));

        calc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        calc.setText("CALCULAR");
        calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcActionPerformed(evt);
            }
        });
        getContentPane().add(calc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("CONCLUIR DEVOLUÇÃO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, -1, 30));

        btn_voltar_FCN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_voltar_FCN.setText("Voltar");
        btn_voltar_FCN.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btn_voltar_FCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltar_FCNActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar_FCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 120, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Login.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 10, 880, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        LocacaoDao ldao = new LocacaoDao();
        Locacao f = new Locacao();
        String campo = "Cliente.cpf"; 
        
        
        
        List<Locacao> loc = ldao.getLista(campo, TXT_CPF.getText());
        DefaultTableModel model = (DefaultTableModel) TBL_CONS.getModel();
        model.setNumRows(0);

        for (Locacao locacao : loc) {
            model.addRow(new Object[]{
                locacao.getId_loc(),
                locacao.getTitulo(),
                locacao.getNome()});
                
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TBL_CONSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_CONSMouseClicked

     
     txt_codloc.setText(TBL_CONS.getValueAt(TBL_CONS.getSelectedRow(),0).toString());
     
    }//GEN-LAST:event_TBL_CONSMouseClicked

    /**
     * @param args the command line arguments
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LocacaoDao ldao = new LocacaoDao();
        Locacao f = new Locacao();
        String campo = "id_loc";  
        
        try {
        ldao.Consulta(campo, txt_codloc.getText(), f);
          if (txt_codloc.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "DIGITE O CODIGO DA LOCAÇÃO !!!");
        } else {
              TXT_DEV.setText(f.getData_dev());
              TXT_VAL.setText(String.valueOf(f.getValor()));
              
          }
    } catch (SQLException ex) {  
        
    }      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcActionPerformed
//       double x = Double.parseDouble(juros.getText());
//       double y = Double.parseDouble(TXT_VAL.getText());
//       double t = Double.parseDouble(atraso.getText());
//       double w;

       if(juros.getText().equals("")){
          
           total.setText(TXT_VAL.getText());
        
        }else{
       double x = Double.parseDouble(juros.getText());
       double y = Double.parseDouble(TXT_VAL.getText());
       double t = Double.parseDouble(atraso.getText());
       double w;    
       w = (((x/100)*y)*t)+y;
           total.setText(String.valueOf(w));
       }
        
    }//GEN-LAST:event_calcActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Locacao l = new Locacao();
            try {
            l.setId_loc(Integer.parseInt(txt_codloc.getText()));
            l.setStatus("Devolvido");

        } catch (Exception e) {
        }
        LocacaoDao ldao = new LocacaoDao();
        ldao.Alterar(l);
        JOptionPane.showMessageDialog(null,"DEVOLUÇÃO CONCLUIDA COM SUCESSO !!!");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_voltar_FCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltar_FCNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu obj = new Menu();
        obj.setVisible(true);
    }//GEN-LAST:event_btn_voltar_FCNActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Devolucao_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Devolucao_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Devolucao_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Devolucao_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Devolucao_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TBL_CONS;
    private javax.swing.JTextField TXT_CPF;
    private javax.swing.JTextField TXT_DEV;
    private javax.swing.JTextField TXT_VAL;
    private javax.swing.JTextField atraso;
    private javax.swing.JButton btn_voltar_FCN;
    private javax.swing.JButton calc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField juros;
    private javax.swing.JTextField total;
    private javax.swing.JTextField txt_codloc;
    // End of variables declaration//GEN-END:variables
}
