/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javalocadora;

import Conection.Conexao;
import Locadora.dao.FilmeDao;
import Locadora.modelo.Filme;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author julio
 */
public class Filme_FL extends javax.swing.JFrame {

public Connection con;
public Statement st;

    /**
     * Creates new form Funcionario
     */
    public Filme_FL() {
        initComponents();
        Conexao FL_Filme = new Conexao();
        FL_TITULO.setEnabled(false);
        FL_DURACAO.setEnabled(false); 
        FL_GENERO.setEnabled(false);
        FL_PRODUTORA.setEnabled(false);
        FL_VALOR.setEnabled(false);
        FL_QUANTIDADE.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FL_TITULO = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CL_DATA_NASCIMENTO = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        FL_QUANTIDADE = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btn_gravar = new javax.swing.JButton();
        FL_GENERO = new javax.swing.JComboBox<>();
        FL_DURACAO = new javax.swing.JFormattedTextField();
        btn_alterar = new javax.swing.JButton();
        FL_PRODUTORA = new javax.swing.JTextField();
        FL_VALOR = new javax.swing.JTextField();
        btn_pesquisar = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("TITULO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        jPanel1.add(FL_TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 400, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Duração");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Genero");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        CL_DATA_NASCIMENTO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CL_DATA_NASCIMENTO.setText("Produtora");
        jPanel1.add(CL_DATA_NASCIMENTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Valor de Locação");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Quantidade");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));
        jPanel1.add(FL_QUANTIDADE, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 140, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setText("Código Filme:");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("DADOS DO FILME");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        btn_voltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 120, 40));

        btn_excluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 130, 40));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Novo");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 80, 30));

        btn_gravar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_gravar.setText("Gravar Filme");
        btn_gravar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gravarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_gravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 140, 40));

        FL_GENERO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ação", "Animação", "Aventura", "Chanchada", "Cinema catástrofe", "Comédia", "Comédia romântica", "Comédia dramática", "Comédia de ação", "Cult", "Dança", "Documentários", "Drama", "Espionagem", "Erótico", "Fantasia", "Faroeste", "Ficção científica", "Franchise/Séries", "Guerra", "Musical", "Policial", "Romance", "Seriado", "Suspense", "Terror (ou horror)", "Trash" }));
        FL_GENERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FL_GENEROActionPerformed(evt);
            }
        });
        jPanel1.add(FL_GENERO, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 170, -1));

        try {
            FL_DURACAO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FL_DURACAO.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(FL_DURACAO, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 140, -1));

        btn_alterar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 130, 40));
        jPanel1.add(FL_PRODUTORA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 130, -1));
        jPanel1.add(FL_VALOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 90, -1));

        btn_pesquisar.setText("BUSCAR");
        btn_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 60, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/tela_file5.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 320));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu obj = new Menu();
        obj.setVisible(true);

    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_gravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gravarActionPerformed
        Filme f = new Filme();
        try {
                f.setDuracao(FL_DURACAO.getText());
                f.setGenero(FL_GENERO.getSelectedItem().toString());
                f.setPreco(Double.parseDouble(FL_VALOR.getText()));
                f.setProdutora(FL_PRODUTORA.getText());
                f.setQtd(Integer.parseInt(FL_QUANTIDADE.getText()));
                f.setTitulo(FL_TITULO.getText());

        } catch (Exception e) {
            
        }
      
        FilmeDao cdao = new FilmeDao();
        cdao.Adiciona(f);
        JOptionPane.showMessageDialog(null,"Filme Cadastrado com Sucesso");
         
    }//GEN-LAST:event_btn_gravarActionPerformed

    private void FL_GENEROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FL_GENEROActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FL_GENEROActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        FL_TITULO.setEnabled(true);
        FL_DURACAO.setEnabled(true); 
        FL_GENERO.setEnabled(true);
        FL_PRODUTORA.setEnabled(true);
        FL_VALOR.setEnabled(true);
        FL_QUANTIDADE.setEnabled(true);
        
        id.setText("");
        FL_TITULO.setText("");
        FL_DURACAO.setText(""); 
        FL_PRODUTORA.setText("");
        FL_VALOR.setText("");
        FL_QUANTIDADE.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed

               Filme Flm = new Filme();
        int r = JOptionPane.showConfirmDialog(null, "Deseja excluir esse Cadastro ?");
            if(r==0){
                Flm.setId_filme(Integer.parseInt(id.getText()));
                FilmeDao cdao = new FilmeDao();
                cdao.remove(Flm);
                JOptionPane.showMessageDialog(null, "Cadastro Excluido com Sucesso");
                
            }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
          Filme f = new Filme();
        try {
            f.setDuracao(FL_DURACAO.getText());
            f.setGenero(FL_GENERO.getSelectedItem().toString());
            f.setPreco(Double.parseDouble(FL_VALOR.getText()));
            f.setProdutora(FL_PRODUTORA.getText());
            f.setQtd(Integer.parseInt(FL_QUANTIDADE.getText()));
            f.setTitulo(FL_TITULO.getText());
        } catch (Exception e) {
        }
        FilmeDao fdao = new FilmeDao();
        fdao.Alterar(f);
        JOptionPane.showMessageDialog(null,"Cadastro Alterado com Sucesso");
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarActionPerformed
        FilmeDao fdao = new FilmeDao();
        Filme f = new Filme();
        String campo = "id_Filme";

    try {
        fdao.Consulta(campo, id.getText(), f);
          if (id.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "DIGITE O CODIGO DO FILME !!!");
        } else {
            FL_DURACAO.setText(f.getDuracao());
            FL_PRODUTORA.setText(f.getProdutora());
            FL_QUANTIDADE.setText(String.valueOf(f.getQtd()));
            FL_TITULO.setText(""+f.getTitulo());
            FL_VALOR.setText(String.valueOf(f.getPreco()));
            id.setText(String.valueOf(f.getId_filme()));
        }
    } catch (SQLException ex) {
        //Logger.getLogger(Filme_FL.class.getName()).log(Level.SEVERE, null, ex);
    }


    }//GEN-LAST:event_btn_pesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Filme_FL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Filme_FL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Filme_FL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Filme_FL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Filme_FL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CL_DATA_NASCIMENTO;
    private javax.swing.JFormattedTextField FL_DURACAO;
    private javax.swing.JComboBox<String> FL_GENERO;
    private javax.swing.JTextField FL_PRODUTORA;
    private javax.swing.JTextField FL_QUANTIDADE;
    private javax.swing.JTextField FL_TITULO;
    private javax.swing.JTextField FL_VALOR;
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_gravar;
    private javax.swing.JButton btn_pesquisar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
