/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javalocadora;

import Locadora.dao.ClienteDao;
import Locadora.dao.FilmeDao;
import Locadora.dao.LocacaoDao;
import Locadora.modelo.Cliente;
import Locadora.modelo.Filme;
import Locadora.modelo.Locacao;
import java.sql.Date;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author julio
 */
public class Form_Locacao extends javax.swing.JFrame {

      int id_cli,id_film1,id_film2,id_film3,id_film4;
    /**
     * Creates new form Form_Locacao
     */
    public Form_Locacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        id_loc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nome_cli = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        flm_1 = new javax.swing.JTextField();
        flm_2 = new javax.swing.JTextField();
        flm_3 = new javax.swing.JTextField();
        flm_4 = new javax.swing.JTextField();
        cod_1 = new javax.swing.JTextField();
        cod_2 = new javax.swing.JTextField();
        cod_3 = new javax.swing.JTextField();
        cod_4 = new javax.swing.JTextField();
        vl_1 = new javax.swing.JTextField();
        vl_2 = new javax.swing.JTextField();
        vl_3 = new javax.swing.JTextField();
        vl_4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        vlr_total = new javax.swing.JTextField();
        dt_loc = new javax.swing.JTextField();
        dt_dev = new javax.swing.JTextField();
        Locacao = new javax.swing.JButton();
        btn_voltar_FCN = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        cpf_cli = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/locacao.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(id_loc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 70, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Codigo da Locação");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Cliente");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Filmes Alugados");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("CODIGOS");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CPF");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("VALORES");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Valor da Locação");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Data da Locação");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Data da Devolução");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));
        getContentPane().add(nome_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 240, -1));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));
        getContentPane().add(flm_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 290, -1));
        getContentPane().add(flm_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 290, -1));
        getContentPane().add(flm_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 290, -1));
        getContentPane().add(flm_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 290, -1));
        getContentPane().add(cod_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 90, -1));
        getContentPane().add(cod_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 90, -1));
        getContentPane().add(cod_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 90, -1));
        getContentPane().add(cod_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 90, -1));

        vl_1.setText("0.0");
        getContentPane().add(vl_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 80, -1));

        vl_2.setText("0.0");
        getContentPane().add(vl_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 80, -1));

        vl_3.setText("0.0");
        getContentPane().add(vl_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 80, -1));

        vl_4.setText("0.0");
        getContentPane().add(vl_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 80, -1));

        jButton2.setText("BUSCAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        jButton3.setText("BUSCAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, -1));

        jButton4.setText("BUSCAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));

        jButton5.setText("BUSCAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, -1));

        vlr_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vlr_totalActionPerformed(evt);
            }
        });
        getContentPane().add(vlr_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 160, -1));
        getContentPane().add(dt_loc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 160, -1));
        getContentPane().add(dt_dev, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 160, -1));

        Locacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Locacao.setText("Locação");
        Locacao.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        Locacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocacaoActionPerformed(evt);
            }
        });
        getContentPane().add(Locacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 130, 30));

        btn_voltar_FCN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_voltar_FCN.setText("Voltar");
        btn_voltar_FCN.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btn_voltar_FCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltar_FCNActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar_FCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 120, 30));

        jButton7.setText("Somar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));
        getContentPane().add(cpf_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 170, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/locacao.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 670, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    ClienteDao cdao = new ClienteDao();
    Cliente c = new Cliente();
    String campo = "cpf";
    
    cdao.Consulta(campo, cpf_cli.getText(), c, jLabel1);
        
    if (cpf_cli.getText().equals("")) {
       JOptionPane.showMessageDialog(null, "Digite o CPF");
        } else {
    nome_cli.setText(""+c.getNome());
    cpf_cli.setText(c.getCpf());
    id_cli = c.getId();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocacaoActionPerformed
                Locacao f = new Locacao();
                
        try {
                LocacaoDao ldao = new LocacaoDao();
                
                f.setTitulo(flm_1.getText());
                f.setData_dev(dt_dev.getText());
                f.setData_loc(dt_loc.getText());
                f.setId_cliente_pk(id_cli);
                f.setId_filme1_pk(id_film1);
                f.setId_filme2_pk(id_film2);
                f.setId_filme3_pk(id_film3);
                f.setId_filme4_pk(id_film4);
                f.setValor(Double.parseDouble(vlr_total.getText()));
                f.setStatus("Não Devolvido");
                ldao.Adiciona(f);
                
              
                         
        } catch (Exception e) {
            
        }
      
        


        JOptionPane.showMessageDialog(null,"Locação Cadastrado com Sucesso");
    }//GEN-LAST:event_LocacaoActionPerformed

    private void btn_voltar_FCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltar_FCNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu obj = new Menu();
        obj.setVisible(true);
    }//GEN-LAST:event_btn_voltar_FCNActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FilmeDao fdao = new FilmeDao();
        Filme f = new Filme();
        String campo = "id_Filme";

    try {
        fdao.Consulta(campo, cod_1.getText(), f);
          if (cod_1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "DIGITE O CODIGO DO FILME !!!");
        } else {
            flm_1.setText(""+f.getTitulo());
            vl_1.setText(String.valueOf(f.getPreco()));
            id_film1 = f.getId_filme();
        
        }
    } catch (SQLException ex) {
        Logger.getLogger(Filme_FL.class.getName()).log(Level.SEVERE, null, ex);
    }     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FilmeDao fdao = new FilmeDao();
        Filme f = new Filme();
        String campo = "id_Filme";

    try {
        fdao.Consulta(campo, cod_2.getText(), f);
                if (cod_2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "DIGITE O CODIGO DO FILME !!!");
        } else {
            flm_2.setText(f.getTitulo());
            vl_2.setText(String.valueOf(f.getPreco()));
            id_film2 = f.getId_filme();
        }
    } catch (SQLException ex) {
        Logger.getLogger(Filme_FL.class.getName()).log(Level.SEVERE, null, ex);
    }     
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        FilmeDao fdao = new FilmeDao();
        Filme f = new Filme();
        String campo = "id_Filme";

    try {
        fdao.Consulta(campo, cod_3.getText(), f);
                if (cod_3.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "DIGITE O CODIGO DO FILME !!!");
        } else {
            flm_3.setText(f.getTitulo());
            vl_3.setText(String.valueOf(f.getPreco()));
            id_film3 = f.getId_filme();
        }
    } catch (SQLException ex) {
        Logger.getLogger(Filme_FL.class.getName()).log(Level.SEVERE, null, ex);
    }     
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        FilmeDao fdao = new FilmeDao();
        Filme f = new Filme();
        String campo = "id_Filme";

    try {
        fdao.Consulta(campo, cod_4.getText(), f);
                if (cod_4.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "DIGITE O CODIGO DO FILME !!!");
        } else {
            flm_4.setText(f.getTitulo());
            vl_4.setText(String.valueOf(f.getPreco()));
            id_film4 = f.getId_filme();
        }
    } catch (SQLException ex) {
        Logger.getLogger(Filme_FL.class.getName()).log(Level.SEVERE, null, ex);
    }     
    }//GEN-LAST:event_jButton5ActionPerformed

    private void vlr_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vlr_totalActionPerformed

    }//GEN-LAST:event_vlr_totalActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        double x = Double.parseDouble(vl_1.getText());
        double y = Double.parseDouble(vl_2.getText());
        double w = Double.parseDouble(vl_3.getText());
        double z = Double.parseDouble(vl_4.getText());
        
        double v = x + y + w + z;
        if (vl_1.getText().equals("0.0")){
        }else;{
       vlr_total.setText(String.valueOf(v));
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Locacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Locacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Locacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Locacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Locacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Locacao;
    private javax.swing.JButton btn_voltar_FCN;
    private javax.swing.JTextField cod_1;
    private javax.swing.JTextField cod_2;
    private javax.swing.JTextField cod_3;
    private javax.swing.JTextField cod_4;
    private javax.swing.JTextField cpf_cli;
    private javax.swing.JTextField dt_dev;
    private javax.swing.JTextField dt_loc;
    private javax.swing.JTextField flm_1;
    private javax.swing.JTextField flm_2;
    private javax.swing.JTextField flm_3;
    private javax.swing.JTextField flm_4;
    private javax.swing.JTextField id_loc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nome_cli;
    private javax.swing.JTextField vl_1;
    private javax.swing.JTextField vl_2;
    private javax.swing.JTextField vl_3;
    private javax.swing.JTextField vl_4;
    private javax.swing.JTextField vlr_total;
    // End of variables declaration//GEN-END:variables
}
