/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javalocadora;

import Conection.Conexao;
import Locadora.dao.FuncionarioDao;
import Locadora.modelo.Funcionario;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author julio
 */
public class Funcionario_FCN extends javax.swing.JFrame {

    public Connection con;
    public Statement st;
    public int idfuncionario;
    /**
     * Creates new form Filme
     */
    public Funcionario_FCN() {
        initComponents();
        Conexao FCN_Funcionario = new Conexao ();
        FCN_NOME.setEnabled(false);
        FCN_RG.setEnabled(false);
        FCN_CPF.setEnabled(false);
        FCN_DATA_NASCIMENTO.setEnabled(false);
        FCN_RUA.setEnabled(false);
        FCN_NUMERO.setEnabled(false);
        FCN_BAIRRO.setEnabled(false);
        FCN_CEP.setEnabled(false);
        FCN_CIDADE.setEnabled(false);
        FCN_ESTADO.setEnabled(false);
        FCN_EMAIL.setEnabled(false);
        FCN_TELEFONE_FIXO.setEnabled(false);
        FCN_CELULAR_1.setEnabled(false);
        FCN_CELULAR_2.setEnabled(false);
        FCN_CELULAR_3.setEnabled(false);
        C_NUMERO.setEnabled(false);
        C_Serie.setEnabled(false );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_pesquisar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FCN_NOME = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FCN_CPF = new javax.swing.JTextField();
        jlabeldn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FCN_BAIRRO = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        FCN_RUA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        FCN_CIDADE = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        FCN_CEP = new javax.swing.JTextField();
        FCN_EMAIL = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        FCN_TELEFONE_FIXO = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        FCN_CELULAR_3 = new javax.swing.JTextField();
        ID_FUNCIONARIO = new javax.swing.JLabel();
        id_fun = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        FCN_NUMERO = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        FCN_ESTADO = new javax.swing.JTextField();
        FCN_CELULAR_2 = new javax.swing.JTextField();
        FCN_CELULAR_1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        FCN_DATA_NASCIMENTO = new javax.swing.JFormattedTextField();
        btn_gravar = new javax.swing.JButton();
        btn_novo = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        C_NUMERO = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        C_Serie = new javax.swing.JTextField();
        btn_alterar = new javax.swing.JButton();
        jlabeldn1 = new javax.swing.JLabel();
        FCN_DATA_CAD = new javax.swing.JFormattedTextField();
        btn_pesquisar1 = new javax.swing.JButton();
        FCN_RG = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();

        btn_pesquisar.setText("PESQUISAR CPF");
        btn_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        jPanel1.add(FCN_NOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 400, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("RG:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("CPF:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));
        jPanel1.add(FCN_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 120, -1));

        jlabeldn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlabeldn.setText("Data Cadastro :");
        jPanel1.add(jlabeldn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Bairro:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));
        jPanel1.add(FCN_BAIRRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 170, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Rua:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));
        jPanel1.add(FCN_RUA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 320, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Cidade:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));
        jPanel1.add(FCN_CIDADE, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("CEP:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));
        jPanel1.add(FCN_CEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 170, -1));
        jPanel1.add(FCN_EMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, 160, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Email:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 570, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Celular");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, -1, -1));
        jPanel1.add(FCN_TELEFONE_FIXO, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 120, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Telefone Fixo:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, -1, -1));
        jPanel1.add(FCN_CELULAR_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 610, 120, -1));

        ID_FUNCIONARIO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ID_FUNCIONARIO.setText("Código Funcionário");
        jPanel1.add(ID_FUNCIONARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        id_fun.setEditable(false);
        jPanel1.add(id_fun, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 50, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Nº");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, -1, -1));
        jPanel1.add(FCN_NUMERO, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 40, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Série:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, -1, -1));
        jPanel1.add(FCN_ESTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 40, -1));
        jPanel1.add(FCN_CELULAR_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 610, 120, -1));
        jPanel1.add(FCN_CELULAR_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 610, 120, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("DADOS PESSOAIS");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Carteira de Trabalho");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("CONTATO");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        try {
            FCN_DATA_NASCIMENTO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FCN_DATA_NASCIMENTO.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        FCN_DATA_NASCIMENTO.setToolTipText("");
        jPanel1.add(FCN_DATA_NASCIMENTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 110, -1));

        btn_gravar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_gravar.setText("Gravar ");
        btn_gravar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gravarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_gravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 140, 40));

        btn_novo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_novo.setText("Novo");
        btn_novo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_novo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 130, 40));

        btn_excluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 650, 130, 40));

        btn_voltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 650, 120, 40));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Estado");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Estado");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Estado");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("ENDEREÇO");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Número:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Número:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));
        jPanel1.add(C_NUMERO, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 200, -1));

        jTextField2.setText("jTextField2");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, -1, -1));
        jPanel1.add(C_Serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 90, -1));

        btn_alterar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 650, 130, 40));

        jlabeldn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlabeldn1.setText("Data Nascimento :");
        jPanel1.add(jlabeldn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        try {
            FCN_DATA_CAD.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FCN_DATA_CAD.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        FCN_DATA_CAD.setToolTipText("");
        jPanel1.add(FCN_DATA_CAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 110, -1));

        btn_pesquisar1.setText("PESQUISAR CPF");
        btn_pesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pesquisar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, -1, -1));
        jPanel1.add(FCN_RG, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 140, -1));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fundo_cliente.jpg"))); // NOI18N
        jLabel20.setAutoscrolls(true);
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gravarActionPerformed
        Funcionario f = new Funcionario();
       
    try {
        f.setNome(FCN_NOME.getText());
        f.setCpf(FCN_CPF.getText());
        f.setCep(FCN_CEP.getText());
        f.setBairro(FCN_BAIRRO.getText());
        f.setCelular1(FCN_CELULAR_1.getText());
        f.setCelular2(FCN_CELULAR_2.getText());
        f.setCelular3(FCN_CELULAR_3.getText());
        f.setCidade(FCN_CIDADE.getText());
        f.setData_cad(FCN_DATA_CAD.getText());
        f.setData_nasc(FCN_DATA_NASCIMENTO.getText());
        f.setEmail(FCN_EMAIL.getText());
        f.setEstado(FCN_ESTADO.getText());
        f.setNum(FCN_NUMERO.getText());
        f.setRg(FCN_RG.getText());
        f.setRua(FCN_RUA.getText());
        f.setTel_fixo(FCN_TELEFONE_FIXO.getText());
        f.setNum_cart(C_NUMERO.getText());
        f.setSerie(C_Serie.getText());
        
    }catch(Exception e){
        
    }
        FuncionarioDao fdao = new FuncionarioDao();
        fdao.Adiciona(f);
        JOptionPane.showMessageDialog(null, "Funcionario Cadastrado com Sucesso !!!");
    }//GEN-LAST:event_btn_gravarActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu obj = new Menu();
        obj.setVisible(true);

    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        
        FCN_NOME.setEnabled(true);
        FCN_RG.setEnabled(true);
        FCN_CPF.setEnabled(true);
        FCN_DATA_NASCIMENTO.setEnabled(true);
        FCN_RUA.setEnabled(true);
        FCN_NUMERO.setEnabled(true);
        FCN_BAIRRO.setEnabled(true);
        FCN_CEP.setEnabled(true);
        FCN_CIDADE.setEnabled(true);
        FCN_ESTADO.setEnabled(true);
        FCN_EMAIL.setEnabled(true);
        FCN_TELEFONE_FIXO.setEnabled(true);
        FCN_CELULAR_1.setEnabled(true);
        FCN_CELULAR_2.setEnabled(true);
        FCN_CELULAR_3.setEnabled(true);
        C_NUMERO.setEnabled(true);
        C_Serie.setEnabled(true);
        
        FCN_NOME.setText("");
        FCN_RG.setText("");
        FCN_CPF.setText("");
        FCN_DATA_NASCIMENTO.setText("");
        FCN_RUA.setText("");
        FCN_NUMERO.setText("");
        FCN_BAIRRO.setText("");
        FCN_CEP.setText("");
        FCN_CIDADE.setText("");
        FCN_ESTADO.setText("");
        FCN_EMAIL.setText("");
        FCN_DATA_CAD.setText("");
        FCN_TELEFONE_FIXO.setText("");
        FCN_CELULAR_1.setText("");
        FCN_CELULAR_2.setText("");
        FCN_CELULAR_3.setText("");
        C_NUMERO.setText("");
        C_Serie.setText("");
        
    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
          Funcionario f = new Funcionario();
        int r = JOptionPane.showConfirmDialog(null, "Deseja excluir esse Cadastro ?");
            if(r==0){
                f.setId_func(Integer.parseInt(id_fun.getText()));
                FuncionarioDao fdao = new FuncionarioDao();
                fdao.remove(f);
                JOptionPane.showMessageDialog(null, "Cadastro Excluido com Sucesso");
                
            }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
         Funcionario f = new Funcionario();
        if (FCN_CPF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o CPF");
        } else {
        try {
        f.setNome(FCN_NOME.getText());
        f.setCpf(FCN_CPF.getText());
        f.setCep(FCN_CEP.getText());
        f.setBairro(FCN_BAIRRO.getText());
        f.setCelular1(FCN_CELULAR_1.getText());
        f.setCelular2(FCN_CELULAR_2.getText());
        f.setCelular3(FCN_CELULAR_3.getText());
        f.setCidade(FCN_CIDADE.getText());
        f.setData_cad(FCN_DATA_CAD.getText());
        f.setData_nasc(FCN_DATA_NASCIMENTO.getText());
        f.setEmail(FCN_EMAIL.getText());
        f.setEstado(FCN_ESTADO.getText());
        f.setNum(FCN_NUMERO.getText());
        f.setRg(FCN_RG.getText());
        f.setRua(FCN_RUA.getText());
        f.setTel_fixo(FCN_TELEFONE_FIXO.getText());
        f.setNum_cart(C_NUMERO.getText());
        f.setSerie(C_Serie.getText());
            
        }catch (Exception e){
            
        }
         FuncionarioDao fdao = new FuncionarioDao();
        fdao.Alterar(f);
        JOptionPane.showMessageDialog(null,"Cadastro Alterado com Sucesso");
    }
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarActionPerformed
        
    }//GEN-LAST:event_btn_pesquisarActionPerformed

    private void btn_pesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisar1ActionPerformed
        FuncionarioDao fdao = new FuncionarioDao();
        Funcionario f = new Funcionario();
        String campo = "cpf";

        fdao.Consulta(campo, FCN_CPF.getText(), f, jLabel1);
          if (FCN_CPF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o CPF");
        } else {
        FCN_NOME.setText(f.getNome());
        FCN_CPF.setText(f.getCpf());
        FCN_CEP.setText(f.getCep());
        FCN_BAIRRO.setText(f.getBairro());
        FCN_CELULAR_1.setText(f.getCelular1());
        FCN_CELULAR_2.setText(f.getCelular2());
        FCN_CELULAR_3.setText(f.getCelular3());
        FCN_CIDADE.setText(f.getCidade());
        FCN_DATA_CAD.setText(f.getData_cad());
        FCN_DATA_NASCIMENTO.setText(f.getData_nasc());
        FCN_EMAIL.setText(f.getEmail());
        FCN_ESTADO.setText(f.getEstado());
        FCN_NUMERO.setText(f.getNum());
        FCN_RG.setText(f.getRg());
        FCN_RUA.setText(f.getRua());
        FCN_TELEFONE_FIXO.setText(f.getTel_fixo());
        C_NUMERO.setText(f.getNum_cart());
        C_Serie.setText(f.getSerie());
        id_fun.setText(String.valueOf(f.getId_func()));
          }
    }//GEN-LAST:event_btn_pesquisar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcionario_FCN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcionario_FCN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcionario_FCN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcionario_FCN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funcionario_FCN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField C_NUMERO;
    private javax.swing.JTextField C_Serie;
    private javax.swing.JTextField FCN_BAIRRO;
    private javax.swing.JTextField FCN_CELULAR_1;
    private javax.swing.JTextField FCN_CELULAR_2;
    private javax.swing.JTextField FCN_CELULAR_3;
    private javax.swing.JTextField FCN_CEP;
    private javax.swing.JTextField FCN_CIDADE;
    private javax.swing.JTextField FCN_CPF;
    private javax.swing.JFormattedTextField FCN_DATA_CAD;
    private javax.swing.JFormattedTextField FCN_DATA_NASCIMENTO;
    private javax.swing.JTextField FCN_EMAIL;
    private javax.swing.JTextField FCN_ESTADO;
    private javax.swing.JTextField FCN_NOME;
    private javax.swing.JTextField FCN_NUMERO;
    private javax.swing.JFormattedTextField FCN_RG;
    private javax.swing.JTextField FCN_RUA;
    private javax.swing.JTextField FCN_TELEFONE_FIXO;
    private javax.swing.JLabel ID_FUNCIONARIO;
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_gravar;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_pesquisar;
    private javax.swing.JButton btn_pesquisar1;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JTextField id_fun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel jlabeldn;
    private javax.swing.JLabel jlabeldn1;
    // End of variables declaration//GEN-END:variables
}
